apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-config
data:
  DB_NAME: coworking
  DB_USER: postgres
  DB_HOST: postgres-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-secrets
type: Opaque
data:
  DB_PASSWORD: <base64-encoded-password>

envFrom:
- configMapRef:
      name: coworking-config
env:
- name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: coworking-secrets
        key: DB_PASSWORD